# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
    ]
