# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='slug-field'),
            preserve_default=False,
        ),
    ]
